amd64 = {
    1: "sys_exit",
    2: "sys_fork",
    3: "sys_read",
    4: "sys_write",
    5: "sys_open",
    6: "sys_close",
    9: "sys_link",
    10: "sys_unlink",
    12: "sys_chdir",
    15: "sys_chmod",
    17: "sys_brk",
    20: "sys_getpid",
    22: "sys_unmount",
    23: "sys_setuid",
    24: "sys_getuid",
    25: "sys_geteuid",
    26: "sys_ptrace",
    33: "sys_access",
    36: "sys_sync",
    37: "sys_kill",
    39: "sys_getppid",
    41: "sys_dup",
    42: "sys_pipe",
    58: "sys_readlink",
    92: "sys_fcntl",
}
